### ISSUE TITLE
Bedrock edition PSupport builds correctly, but cannot join world.

### ISSUE THREAD

**Issue by Lauriethefish** [Xernium/ProtocolSupport-Bedrock-Dev#45]
I managed to Successfully build the plugin, and when I put it on my test server (1.13) it started up correctly. It said that it had started the Bedrock threads. But when I tried to connect to it, bedrock edition said "Unable to connect to world" The Port and IP are both correct.

Even with debug enabled, nothing shows up in the console.

**Comment by Xernium** [comment]
Is the file size over 20 mb? If yes is the server query disabled or on another port? Is UDP open on the game port? If your minecraft port is 25565 it’s also 25565 for bedrock edition. The firewall needs to both accept TCP and UDP for this to work

**Comment by Lauriethefish** [comment]
File size is ~ 50mb. Server query is enabled, the server is on my PC so firewall shouldn't effect it.
I can connect to it in 1.12.2 so the plugin is working.

**Comment by Lauriethefish** [comment]
Hello?

**Comment by Xernium** [comment]
You’re a bit too pushy for my liking. If you are running this on windows then ensure loopback works correctly. Also firewall is going to be an issue regardless if it’s on the same computer or not. If it says it started the threads then I can’t help. The issue is in the pipeline there. Try a NukkitX server on the same port and if that works please open a new issue request
